sudo: required
dist: trusty
language: node_js
node_js:
    - '8'

matrix:
    fast_finish: true

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

install:
    - npm install

branches:
    only:
        - develop
        - master

script:
    - npm run ci:travis

cache:
    yarn: true
    directories:
        - node_modules
