sudo: required
dist: trusty
language: node_js
node_js:
    - '8'

matrix:
    fast_finish: true

before_script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
    - export PATH=$HOME/.yarn/bin:$PATH
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

install:
    - yarn install

branches:
    only:
        - master

script:
    - yarn ci
    - yarn global add codecov

after_success:
    - codecov

cache:
    yarn: true
    directories:
        - node_modules
        - $HOME/.electron
        - $HOME/.cache/electron-builder
